import React, { useEffect, useMemo, useState } from 'react';
import { Heart, ArrowLeft, Plus, Pencil, Trash2, X, Clock3, Users, Flame, ChefHat, Utensils, Search } from 'lucide-react';
import './styles.css';

const categories = ['All', 'Chicken', 'Beef', 'Seafood', 'Vegetarian', 'Pasta', 'Breakfast', 'Dessert', 'Soup', 'Salad', 'Baking'];
const starterRecipes = [
  { id: '1', name: 'Creamy Garlic Chicken', category: 'Chicken', image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80', description: 'Tender chicken in a silky garlic cream sauce.', ingredients: [['Chicken breast', '2 pieces'], ['Garlic', '4 cloves'], ['Heavy cream', '1 cup'], ['Parmesan', '½ cup']], instructions: 'Season and sear the chicken until golden. Sauté garlic, add cream and Parmesan, then simmer. Return chicken to the pan and serve.', time: '35 min', servings: '2', calories: '520 kcal', difficulty: 'Easy' },
  { id: '2', name: 'Mediterranean Pasta', category: 'Pasta', image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80', description: 'Bright pasta with tomatoes, herbs and feta.', ingredients: [['Penne pasta', '250 g'], ['Cherry tomatoes', '2 cups'], ['Feta cheese', '100 g'], ['Basil', '1 handful']], instructions: 'Boil pasta until al dente. Toss with roasted tomatoes, basil and feta. Season and serve warm.', time: '25 min', servings: '4', calories: '410 kcal', difficulty: 'Easy' },
  { id: '3', name: 'Herb Crusted Salmon', category: 'Seafood', image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80', description: 'Flaky salmon with a fresh herb crust.', ingredients: [['Salmon fillets', '2'], ['Breadcrumbs', '½ cup'], ['Parsley', '2 tbsp'], ['Lemon', '1']], instructions: 'Top salmon with breadcrumbs and herbs. Bake at 200°C until flaky, then finish with lemon.', time: '30 min', servings: '2', calories: '380 kcal', difficulty: 'Medium' },
  { id: '4', name: 'Garden Buddha Bowl', category: 'Vegetarian', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80', description: 'Colorful vegetables, grains and a creamy dressing.', ingredients: [['Quinoa', '1 cup'], ['Avocado', '1'], ['Mixed greens', '2 cups'], ['Tahini', '2 tbsp']], instructions: 'Cook quinoa and arrange with greens and vegetables. Whisk tahini with lemon and drizzle over the bowl.', time: '20 min', servings: '2', calories: '350 kcal', difficulty: 'Easy' },
  { id: '5', name: 'Classic Beef Tacos', category: 'Beef', image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=900&q=80', description: 'Juicy spiced beef tucked into warm tortillas.', ingredients: [['Ground beef', '500 g'], ['Tortillas', '8'], ['Tomato', '1'], ['Cilantro', '1 handful']], instructions: 'Brown beef with spices. Warm tortillas and fill with beef, tomato, cilantro and your favorite toppings.', time: '30 min', servings: '4', calories: '460 kcal', difficulty: 'Easy' },
  { id: '6', name: 'Berry Pancakes', category: 'Breakfast', image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80', description: 'Fluffy pancakes bursting with fresh berries.', ingredients: [['Flour', '1½ cups'], ['Milk', '1 cup'], ['Eggs', '2'], ['Berries', '1 cup']], instructions: 'Whisk batter ingredients. Cook spoonfuls on a hot griddle and fold through berries. Serve with syrup.', time: '20 min', servings: '3', calories: '290 kcal', difficulty: 'Easy' },
  { id: '7', name: 'Tomato Basil Soup', category: 'Soup', image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80', description: 'Comforting roasted tomato soup with basil.', ingredients: [['Tomatoes', '8'], ['Onion', '1'], ['Vegetable stock', '3 cups'], ['Basil', '1 handful']], instructions: 'Roast tomatoes and onion. Blend with stock until smooth, simmer and finish with fresh basil.', time: '45 min', servings: '4', calories: '180 kcal', difficulty: 'Easy' },
  { id: '8', name: 'Chocolate Lava Cake', category: 'Dessert', image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80', description: 'Warm chocolate cake with a molten center.', ingredients: [['Dark chocolate', '150 g'], ['Butter', '100 g'], ['Eggs', '3'], ['Sugar', '½ cup']], instructions: 'Melt chocolate and butter. Fold into beaten eggs and sugar. Bake in ramekins until edges set and centers wobble.', time: '25 min', servings: '4', calories: '510 kcal', difficulty: 'Medium' },
  { id: '9', name: 'Crisp Garden Salad', category: 'Salad', image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80', description: 'A crisp, refreshing salad for every table.', ingredients: [['Lettuce', '1 head'], ['Cucumber', '1'], ['Tomatoes', '2'], ['Olive oil', '2 tbsp']], instructions: 'Chop all vegetables and combine. Dress with olive oil, lemon, salt and pepper just before serving.', time: '10 min', servings: '2', calories: '140 kcal', difficulty: 'Easy' },
  { id: '10', name: 'Rustic Apple Pie', category: 'Baking', image: 'https://images.unsplash.com/photo-1535920527002-b35e96722eb9?auto=format&fit=crop&w=900&q=80', description: 'Golden pastry wrapped around cinnamon apples.', ingredients: [['Apples', '5'], ['Pie pastry', '1 sheet'], ['Cinnamon', '1 tsp'], ['Brown sugar', '½ cup']], instructions: 'Fill pastry with sliced cinnamon apples. Fold the edges and bake until deeply golden and bubbling.', time: '60 min', servings: '8', calories: '330 kcal', difficulty: 'Medium' }
];

function App() {
  const [page, setPage] = useState('home');
  const [category, setCategory] = useState('All');
  const [selected, setSelected] = useState(null);
  const [favorites, setFavorites] = useState(() => JSON.parse(localStorage.getItem('foodie-favorites') || '[]'));
  const [custom, setCustom] = useState(() => JSON.parse(localStorage.getItem('foodie-custom') || '[]'));
  const [editing, setEditing] = useState(null);
  const [query, setQuery] = useState('');
  useEffect(() => localStorage.setItem('foodie-favorites', JSON.stringify(favorites)), [favorites]);
  useEffect(() => localStorage.setItem('foodie-custom', JSON.stringify(custom)), [custom]);
  const all = [...starterRecipes, ...custom];
  const visible = useMemo(() => all.filter(r => (category === 'All' || r.category === category) && r.name.toLowerCase().includes(query.toLowerCase())), [all, category, query]);
  const toggleFavorite = (recipe) => setFavorites(list => list.some(r => r.id === recipe.id) ? list.filter(r => r.id !== recipe.id) : [...list, recipe]);
  const open = recipe => { setSelected(recipe); setPage('detail'); };
  const saveRecipe = data => { setCustom(list => editing ? list.map(r => r.id === editing.id ? {...data, id: editing.id, category: 'My Recipes'} : r) : [...list, {...data, id: `custom-${Date.now()}`, category: 'My Recipes'}]); setEditing(null); setPage('my-food'); };
  return <div className="app">
    <header className="topbar"><button className="logo" onClick={() => setPage('home')}><span>🍴</span> Foodie<span className="dot">.</span></button><nav><button className={page === 'home' ? 'active' : ''} onClick={() => setPage('home')}>Discover</button><button className={page === 'favorites' ? 'active' : ''} onClick={() => setPage('favorites')}>Favorites <b>{favorites.length}</b></button><button className={page === 'my-food' ? 'active' : ''} onClick={() => setPage('my-food')}>My Food</button></nav><label className="search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search recipes..."/></label></header>
    {page === 'home' && <><section className="hero"><div><p className="eyebrow">GOOD FOOD · GOOD MOOD</p><h1>Make something<br/><em>delicious</em> today.</h1><p>Discover recipes made for real life, from quick weekday meals to dishes worth sharing.</p><button className="primary" onClick={() => document.getElementById('recipes').scrollIntoView({behavior:'smooth'})}>Explore recipes <span>→</span></button></div><div className="hero-image"><img src={starterRecipes[0].image}/><div className="floating">♡ <strong>{favorites.length}</strong><small> saved recipes</small></div></div></section><main id="recipes" className="content"><div className="section-heading"><div><p className="eyebrow">FIND YOUR FAVORITE</p><h2>Browse by category</h2></div><span>{visible.length} recipes</span></div><div className="categories">{categories.map(c => <button key={c} className={category === c ? 'selected' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div><div className="recipe-grid">{visible.map(r => <RecipeCard key={r.id} recipe={r} favorite={favorites.some(f => f.id === r.id)} onOpen={open} onFavorite={toggleFavorite}/>)}</div></main></>}
    {page === 'favorites' && <Collection title="My Favorite Recipes" subtitle="The recipes you never want to lose." recipes={favorites} empty="No favorite recipes yet. Tap the heart on a recipe to save it." onOpen={open} onFavorite={toggleFavorite} favorites={favorites}/>} 
    {page === 'my-food' && <MyFood recipes={custom} onAdd={() => {setEditing(null);setPage('form')}} onEdit={r => {setEditing(r);setPage('form')}} onDelete={r => setCustom(list => list.filter(x => x.id !== r.id))} onOpen={open}/>} 
    {page === 'detail' && selected && <Detail recipe={selected} favorite={favorites.some(f => f.id === selected.id)} onFavorite={() => toggleFavorite(selected)} onBack={() => setPage(selected.category === 'My Recipes' ? 'my-food' : 'home')}/>} 
    {page === 'form' && <RecipeForm initial={editing} onSave={saveRecipe} onCancel={() => setPage('my-food')}/>} 
    <footer>Foodie<span className="dot">.</span> <span>Made with love for home cooks.</span></footer>
  </div>;
}

function RecipeCard({recipe, favorite, onOpen, onFavorite}) { return <article className="card"><div className="card-image" onClick={() => onOpen(recipe)}><img src={recipe.image}/><button className={'heart ' + (favorite ? 'liked' : '')} onClick={e => {e.stopPropagation();onFavorite(recipe)}}>{favorite ? '♥' : '♡'}</button><span className="tag">{recipe.category}</span></div><div className="card-body" onClick={() => onOpen(recipe)}><h3>{recipe.name}</h3><p>{recipe.description}</p><div className="meta"><span>◷ {recipe.time}</span><span>·</span><span>{recipe.difficulty}</span></div></div></article> }
function Collection({title, subtitle, recipes, empty, onOpen, onFavorite, favorites}) { return <main className="content collection"><button className="back" onClick={() => window.history.length > 1 ? null : null}>← Discover</button><div className="section-heading"><div><p className="eyebrow">YOUR COLLECTION</p><h2>{title}</h2><p>{subtitle}</p></div><span>{recipes.length} saved</span></div>{recipes.length ? <div className="recipe-grid">{recipes.map(r => <RecipeCard key={r.id} recipe={r} favorite={favorites.some(f => f.id === r.id)} onOpen={onOpen} onFavorite={onFavorite}/>)}</div> : <div className="empty">♡<h3>{empty}</h3></div>}</main> }
function Detail({recipe, favorite, onFavorite, onBack}) { return <main className="detail"><button className="back" onClick={onBack}>← Back</button><div className="detail-grid"><img className="detail-image" src={recipe.image}/><div className="detail-copy"><span className="tag static">{recipe.category}</span><h1>{recipe.name}</h1><p className="lead">{recipe.description}</p><button className={'favorite-button ' + (favorite ? 'liked' : '')} onClick={onFavorite}>{favorite ? '♥ Saved to favorites' : '♡ Save to favorites'}</button><div className="stats"><span><Clock3/> <b>{recipe.time}</b><small>Prep time</small></span><span><Users/> <b>{recipe.servings}</b><small>Servings</small></span><span><Flame/> <b>{recipe.calories}</b><small>Calories</small></span><span><ChefHat/> <b>{recipe.difficulty}</b><small>Difficulty</small></span></div><div className="detail-section"><h2>Ingredients</h2><ul>{recipe.ingredients.map(([name, amount]) => <li key={name}><span>{name}</span><b>{amount}</b></li>)}</ul></div><div className="detail-section"><h2>Instructions</h2><p className="instructions">{recipe.instructions}</p></div></div></div></main> }
function MyFood({recipes, onAdd, onEdit, onDelete, onOpen}) { return <main className="content my-food"><div className="section-heading"><div><p className="eyebrow">YOUR KITCHEN</p><h2>My Recipes</h2><p>Recipes you created, all in one place.</p></div><button className="primary" onClick={onAdd}><Plus size={18}/> Add New Recipe</button></div>{recipes.length ? <div className="my-list">{recipes.map(r => <article className="my-item" key={r.id}><img src={r.image || 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=400&q=80'} onClick={() => onOpen(r)}/><div onClick={() => onOpen(r)}><h3>{r.name}</h3><p>{(r.description || '').slice(0, 100)}{r.description?.length > 100 ? '...' : ''}</p></div><div className="actions"><button onClick={() => onEdit(r)}><Pencil size={16}/> Edit</button><button className="danger" onClick={() => onDelete(r)}><Trash2 size={16}/> Delete</button></div></article>)}</div> : <div className="empty"><ChefHat/><h3>Your recipe book is empty.</h3><button className="primary" onClick={onAdd}>Add your first recipe</button></div>}</main> }
function RecipeForm({initial, onSave, onCancel}) { const [name,setName]=useState(initial?.name || ''); const [image,setImage]=useState(initial?.image || ''); const [description,setDescription]=useState(initial?.description || ''); const [ingredients,setIngredients]=useState(initial?.ingredients?.map(x => x.join(' — ')).join('\n') || ''); const [instructions,setInstructions]=useState(initial?.instructions || ''); return <main className="form-page"><button className="back" onClick={onCancel}>← My Recipes</button><div className="form-card"><p className="eyebrow">{initial ? 'EDIT RECIPE' : 'NEW RECIPE'}</p><h1>{initial ? 'Edit your recipe' : 'Share a recipe'}</h1><p>Fill in the details below to add it to your personal cookbook.</p><label>Recipe name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Grandma's lasagna"/></label><label>Image URL<input value={image} onChange={e=>setImage(e.target.value)} placeholder="Paste an image URL"/></label>{image && <img className="preview" src={image}/>}<label>Short description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What makes this recipe special?"/></label><label>Ingredients <small>one per line, optionally add amount after —</small><textarea value={ingredients} onChange={e=>setIngredients(e.target.value)} placeholder={'Pasta — 250 g\nTomatoes — 2 cups'}/></label><label>Step-by-step instructions<textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Describe how to prepare your recipe..."/></label><div className="form-actions"><button className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={!name.trim()} onClick={()=>onSave({name,image:image || 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=900&q=80',description,ingredients:ingredients.split('\n').filter(Boolean).map(x=>{const [a,b] = x.split('—'); return [a.trim(),(b || '').trim()] }),instructions,time:'Custom',servings:'—',calories:'—',difficulty:'Personal'})}>Save Recipe</button></div></div></main> }
export default App;
